# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/midterm_1_practice/midterm_1_practice.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==midterm_1_practice || ORIG_REF_NAME==midterm_1_practice} -quiet] -quiet

# IP: bd/midterm_1_practice/ip/midterm_1_practice_processing_system7_0_0/midterm_1_practice_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==midterm_1_practice_processing_system7_0_0 || ORIG_REF_NAME==midterm_1_practice_processing_system7_0_0} -quiet] -quiet

# IP: bd/midterm_1_practice/ip/midterm_1_practice_axi_gpio_0_0/midterm_1_practice_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==midterm_1_practice_axi_gpio_0_0 || ORIG_REF_NAME==midterm_1_practice_axi_gpio_0_0} -quiet] -quiet

# IP: bd/midterm_1_practice/ip/midterm_1_practice_xbar_0/midterm_1_practice_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==midterm_1_practice_xbar_0 || ORIG_REF_NAME==midterm_1_practice_xbar_0} -quiet] -quiet

# IP: bd/midterm_1_practice/ip/midterm_1_practice_ps7_0_axi_periph_0/midterm_1_practice_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==midterm_1_practice_ps7_0_axi_periph_0 || ORIG_REF_NAME==midterm_1_practice_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/midterm_1_practice/ip/midterm_1_practice_rst_ps7_0_100M_0/midterm_1_practice_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==midterm_1_practice_rst_ps7_0_100M_0 || ORIG_REF_NAME==midterm_1_practice_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/midterm_1_practice/ip/midterm_1_practice_axi_gpio_0_1/midterm_1_practice_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==midterm_1_practice_axi_gpio_0_1 || ORIG_REF_NAME==midterm_1_practice_axi_gpio_0_1} -quiet] -quiet

# IP: bd/midterm_1_practice/ip/midterm_1_practice_axi_gpio_0_4/midterm_1_practice_axi_gpio_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==midterm_1_practice_axi_gpio_0_4 || ORIG_REF_NAME==midterm_1_practice_axi_gpio_0_4} -quiet] -quiet

# IP: bd/midterm_1_practice/ip/midterm_1_practice_auto_pc_0/midterm_1_practice_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==midterm_1_practice_auto_pc_0 || ORIG_REF_NAME==midterm_1_practice_auto_pc_0} -quiet] -quiet

# XDC: bd/midterm_1_practice/midterm_1_practice_ooc.xdc
