# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CSULB_Classes/CECS_461/Mideterm_1_Review/midterm_1_practice/midterm_1_practice.srcs/sources_1/bd/midterm_1_practice/ip/midterm_1_practice_axi_gpio_0_4/midterm_1_practice_axi_gpio_0_4.xci
# IP: The module: 'midterm_1_practice_axi_gpio_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CSULB_Classes/CECS_461/Mideterm_1_Review/midterm_1_practice/midterm_1_practice.srcs/sources_1/bd/midterm_1_practice/ip/midterm_1_practice_axi_gpio_0_4/midterm_1_practice_axi_gpio_0_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'midterm_1_practice_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/CSULB_Classes/CECS_461/Mideterm_1_Review/midterm_1_practice/midterm_1_practice.srcs/sources_1/bd/midterm_1_practice/ip/midterm_1_practice_axi_gpio_0_4/midterm_1_practice_axi_gpio_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'midterm_1_practice_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/CSULB_Classes/CECS_461/Mideterm_1_Review/midterm_1_practice/midterm_1_practice.srcs/sources_1/bd/midterm_1_practice/ip/midterm_1_practice_axi_gpio_0_4/midterm_1_practice_axi_gpio_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'midterm_1_practice_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/CSULB_Classes/CECS_461/Mideterm_1_Review/midterm_1_practice/midterm_1_practice.srcs/sources_1/bd/midterm_1_practice/ip/midterm_1_practice_axi_gpio_0_4/midterm_1_practice_axi_gpio_0_4.xci
# IP: The module: 'midterm_1_practice_axi_gpio_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CSULB_Classes/CECS_461/Mideterm_1_Review/midterm_1_practice/midterm_1_practice.srcs/sources_1/bd/midterm_1_practice/ip/midterm_1_practice_axi_gpio_0_4/midterm_1_practice_axi_gpio_0_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'midterm_1_practice_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/CSULB_Classes/CECS_461/Mideterm_1_Review/midterm_1_practice/midterm_1_practice.srcs/sources_1/bd/midterm_1_practice/ip/midterm_1_practice_axi_gpio_0_4/midterm_1_practice_axi_gpio_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'midterm_1_practice_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/CSULB_Classes/CECS_461/Mideterm_1_Review/midterm_1_practice/midterm_1_practice.srcs/sources_1/bd/midterm_1_practice/ip/midterm_1_practice_axi_gpio_0_4/midterm_1_practice_axi_gpio_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'midterm_1_practice_axi_gpio_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
